### ISSUE TITLE
Integrate pytest instead of nosetests

### ISSUE THREAD

**Issue by naspeh** [superdesk/newsroom#8]
pytest is modern tool for testing in Python world. It is active, the latest version from 2017-08-09.

The latest version of `nose`: https://pypi.python.org/pypi/nose/1.3.7 from 2015-06-02
There is also `nose2` (same author) https://pypi.python.org/pypi/nose2/0.6.5 from 2016-06-29

Docs: https://docs.pytest.org/en/latest/
For BDD: https://pypi.python.org/pypi/pytest-bdd

`newsroom` project has a little tests yet, so it'll be easy to transform it, I can help with this step.

@petrjasek, @akintolga what do you think?

**Comment by petrjasek** [comment]
looks good, be my guest :wink:

**Comment by akintolga** [comment]
Sounds good to me to 👍

**Comment by naspeh** [comment]
Great, I'm going to integrate it today

**Comment by naspeh** [comment]
Ready in #9 :)
